server:
  port: 8082

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./data/client
    type: com.zaxxer.hikari.HikariDataSource
    username: sa
    password: password
  h2:
    console:
      enabled: true
